title: "Axial Residual Networks for CycleGAN-based Voice Conversion"
description: "Authors: Jaeseong You, Gyuhyeon Nam, Dalhyun Kim, Gyeongsu Chae<br>ArXiv: <a href='https://arxiv.org/abs/2102.08075'>arXiv:2102.08075</a>"
show_downloads: true
google_analytics:
theme: jekyll-theme-architect